In [1]:
# commented line

In [155]:
#=
multiple
commented 
lines
=#

#=multiple
commented 
lines=#

In [156]:
#mandatory new language greeting
print("Hello World!")

Hello World!

In [157]:
#variable assignment 
x = 10

10

In [158]:
#reassignment
x = 100
println(x)

100


In [159]:
#make it a constant
const y = 1000

1000

In [161]:
#attempt to reassign it, it does not produce an 'error' but produces a 'warning'
#still mutable
y = 1

1

In [162]:
#still reassigns though
println(y)

1


In [163]:
#assign mutliple variables at once
a,b,c = 20, 40, 60
println(a)
println(b)
println(c)

20
40
60


In [10]:
#standard aritmetic
t_0 = 10
#addition
t_1 = t_0 + 1
#print a descriptive string and the value
println("t_0 + 1 = ", t_1)
#subtraction
t_2 = t_0 - t_1
#print the number within a string that is called 'string interpolation'
#using $() placing the variable inside the parenthesis
println("t_0 - t_1 = $(t_2)")
#compute a multiplication inside the string interpolation
println("multiplication of t_2 * 10 = $( t_2*10 )")
#exponentiation, and we can have multiple commands per line when commands are separated by semicolons ';'
t_3 = t_0 ^ 2; println("t_3 = t_0 ^ 2 = $(t_3)")
#division
t_4 = t_0 / 2; println("t_4 = t_0 / 2 = $(t_4)")
# division
t_5 = t_0 / 3; println("t_5 = t_0 / 3 = $(t_5)")
# make fractions
t_6 = t_0 // 3; println("t_6 = t_0 // 3 = $(t_6)")
# add fractions together
t_7 = (t_0 // 3) + (7 // 4); println("t_7 = (t_0 // 3) + (7 // 4) = $(t_7)")

t_0 + 1 = 11
t_0 - t_1 = -1
multiplication of t_2 * 10 = -10
t_3 = t_0 ^ 2 = 100
t_4 = t_0 / 2 = 5.0
t_5 = t_0 / 3 = 3.3333333333333335
t_6 = t_0 // 3 = 10//3
t_7 = (t_0 // 3) + (7 // 4) = 61//12


In [75]:
# strings
s1 = "Howdy!"
println(s1)
# we can do string interpolation with a string
println("s1 = $(s1)")
# concatenate strings
s2 = s1 * " How are you?"
println(s2)
# length of a string
s2_length = length(s2)
println("length of s2 = $(s2_length)")
# subset of the strings (treat like an array)
s3 = s2[1:12]
println("s2 from 1 to 12 = $(s3)")
s4 = s2[5:12]
println("s2 from 5 to 12 = $(s4)")
# removing part of a string
s5 = s2[1:3] * s2[6:end]
println("s2 from 1 to 3 and then 6 to the end = $(s5)")
# string interpolation shorthand not needing the parenthesis
s6 = "hello"
println("s6 = $s6")
# substring replace
s7 = replace(s2, "Howdy" => "Hiya")
println("s7 = $s7")
# multiple substring replace using the pairs operator '=>'
s7 = replace(s2, "Howdy" => "Hiya", "How" => "What")
println("s7 = $s7")
# we can make a string with the 'string' constructor
s8 = string(s7, "Are you good?")
println("s8 = $s8")

Howdy!
s1 = Howdy!
Howdy! How are you?
length of s2 = 19
s2 from 1 to 12 = Howdy! How a
s2 from 5 to 12 = y! How a
s2 from 1 to 3 and then 6 to the end = How! How are you?
s6 = hello
s7 = Hiya! How are you?
s7 = Hiya! What are you?
s8 = Hiya! What are you?Are you good?


In [164]:
#build up a string from characters
c1 = 'H'
c2 = 'i'
c_str = string(c1,c2)
println("c_str = ",c_str)

c_str = Hi


In [77]:
string( 'c' + 100, 'c' + 200)

"Çī"

In [170]:
Char(Int('c')+87)

'º': Unicode U+00BA (category Lo: Letter, other)

In [173]:
Char.([55,123,43,444])

4-element Vector{Char}:
 '7': ASCII/Unicode U+0037 (category Nd: Number, decimal digit)
 '{': ASCII/Unicode U+007B (category Ps: Punctuation, open)
 '+': ASCII/Unicode U+002B (category Sm: Symbol, math)
 'Ƽ': Unicode U+01BC (category Lu: Letter, uppercase)

In [175]:
#specify the types at declaration 
q::Int = 10
r::Int64 = 20
s::Float64 = 3.14
t::String = "Hi!"
u = "Hey"
f::UInt8 = 4

4

In [79]:
#get the type of 'q'
typeof(q)

Int64

In [80]:
#check the type of 'q' against another
isa(q,Int)

true

In [81]:
#check the type of 'q' against another 'sibling' of Number
isa(q,Float64)

false

In [82]:
#check the type of 'q' against another parent type
isa(q,Number)

true

In [83]:
#check against the wrong type
q::String

LoadError: TypeError: in typeassert, expected String, got a value of type Int64

In [84]:
#check against the parent type as an assertion
q::Number

10

In [176]:
f = 55

55

In [177]:
f = -3

LoadError: InexactError: trunc(UInt8, -3)

In [178]:
z::Int32 = 1
println(typeof(x),", ", typeof(z) <: Number) 
println(typeof(x),", ", typeof(z) <: Int32)
println(typeof(x),", ", typeof(z) <: Int64)
println(typeof(x),", ", typeof(z) <: Int8)
println(typeof(x),", ", typeof(z) <: Char) 
println(typeof(x),", ", typeof(z) <: Real) 

Int64, true
Int64, true
Int64, false
Int64, false
Int64, false
Int64, true


In [179]:
#convert types
z_float = Float16(z)

Float16(1.0)

In [180]:
typeof(z_float)

Float16

In [181]:
#typecasting for compatibility in operations
a1::Float16 = 2
a2::Float64 = 3
b1::Int8 = 4
a4 = a1+a2+b1
typeof(a4)

Float64

In [182]:
#custom types
#immutable structs, the fields cannot be modified after defining them
struct Point
    x::Float64
    y::Float64
end

In [183]:
p1 = Point(1,2)

Point(1.0, 2.0)

In [184]:
println("x = ", p1.x," y = ",p1.y)

x = 1.0 y = 2.0


In [185]:
#try to change the values
p1.x = 3

LoadError: setfield!: immutable struct of type Point cannot be changed

In [186]:
#now we can define a mutable struct which allows modifying the values
mutable struct MutablePoint
    x::Float64
    y::Float64
end

In [187]:
mp = MutablePoint(1.0, 2.0)
mp.x = 3.0 

3.0

In [188]:
#we don't have to define types
mutable struct Names
    first
    last
end

In [189]:
nms = Names("alex","manz")

Names("alex", "manz")

In [191]:
#we can put commas and semicolons if we wish but must be consistent
mutable struct NamesA
    first,
    last
end
mutable struct NamesB2
    first
    last
end

In [98]:
mutable struct NamesC
    first; last; phone
end

In [99]:
mutable struct NamesE
    first; last; phone
end

In [192]:
#we can make 'parametric types(structs)' they are akin to Generics
struct parametricUser{T}
    userID::T
    userName
end

In [193]:
pu1 = parametricUser( Float16(123), "John" )

parametricUser{Float16}(Float16(123.0), "John")

In [102]:
println( pu1.userID )
println( typeof(pu1.userID) )

123.0
Float16


In [194]:
pu1 = parametricUser( 'z', "John" )

parametricUser{Char}('z', "John")

In [103]:
#we can make 'parametric types(structs)' with multiple parametric types and constrainst
struct parametricUserB{T1,T2<:Int,T3<:String}
    userID::T1
    count::T2
    userName::T3
    appID::T1
end

In [104]:
# ok
parametricUserB(123,2,"John",21)

parametricUserB{Int64, Int64, String}(123, 2, "John", 21)

In [105]:
# not ok, violates type constraint T3
parametricUserB(123,2,0,21)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[103]:3

In [106]:
# not ok, violates type constraint T2
parametricUserB(123,1.2,"John",21)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Float64, ::String, ::Int64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[103]:3

In [107]:
# not ok, violates type constraint for 'userID' and 'appID' to be the same
parametricUserB(123,12,"John",1.2)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Int64, ::String, ::Float64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[103]:3

In [108]:
# inner constructor
struct PositivePoint
    x::Float64
    y::Float64
    PositivePoint(x, y) = x > 0 && y > 0 ? new(x, y) : throw(ArgumentError("Coordinates must be positive"))
end

In [109]:
pp1 = PositivePoint(2,3.3)

PositivePoint(2.0, 3.3)

In [110]:
pp2 = PositivePoint(2,-3.3)

LoadError: ArgumentError: Coordinates must be positive

In [111]:
# different inner constructors
# Inner constructors are defined 
# inside the struct block and can enforce invariants or provide default values
struct PersonType2
    firstName
    lastName
    PersonType2(firstName,lastName) = new(firstName,lastName)
    PersonType2() = new("John","Doe")
end

In [112]:
pt2a = PersonType2()
println(pt2a)
pt2b = PersonType2("Bob","Minton")
println(pt2b)

PersonType2("John", "Doe")
PersonType2("Bob", "Minton")


In [113]:
#let us add optional arguments as well to simplify and expand to more use cases
struct PersonType3
    firstName
    lastName
    function PersonType3(firstName="John", lastName="Doe")
        new(firstName,lastName)
    end
end

In [114]:
pt3a = PersonType3()
println(pt3a)
pt3b = PersonType3("Bob")
println(pt3b)

PersonType3("John", "Doe")
PersonType3("Bob", "Doe")


In [115]:
# fails
pt3c = PersonType3(lastname="Minton")
println(pt3c)

LoadError: MethodError: no method matching PersonType3(; lastname="Minton")
Closest candidates are:
  PersonType3() at In[113]:5 got unsupported keyword argument "lastname"
  PersonType3(::Any) at In[113]:5 got unsupported keyword argument "lastname"
  PersonType3(::Any, ::Any) at In[113]:5 got unsupported keyword argument "lastname"

In [203]:
#adding for keyword arguments
struct PersonType4z
    id
    firstName
    lastName
    function PersonType4z(id;firstName="John", lastName="Doe") #added a semicolon
        new(id,firstName,lastName)
    end
end

In [207]:
pt4a = PersonType4z(1)
println(pt4a)
PersonType4z(2,lastName="baker",firstName="bob")

PersonType4z(1, "John", "Doe")


PersonType4z(2, "bob", "baker")

In [208]:
# inner constructor and keyword arguments
struct PersonType6
    firstName
    lastName
    function PersonType6(;firstName=nothing, lastName=nothing)
        # Check if firstName was provided
        if firstName === nothing
            println("firstName was not provided, using default.")
            firstName = "John"
        end

        # Check if lastName was provided
        if lastName === nothing
            println("lastName was not provided, using default.")
            lastName = "Doe"
        end

        return new(firstName, lastName)
    end
end

In [209]:
pt6a = PersonType6()
println(pt6a)
pt6c = PersonType6(lastName="Minton")
println(pt6c)
pt6d = PersonType6(firstName="Bob")
println(pt6d)
pt6e = PersonType6(firstName="Bob",lastName="Minton")
println(pt6e)

firstName was not provided, using default.
lastName was not provided, using default.
PersonType6("John", "Doe")
firstName was not provided, using default.
PersonType6("John", "Minton")
lastName was not provided, using default.
PersonType6("Bob", "Doe")
PersonType6("Bob", "Minton")


In [211]:
r = 1000
r < 100 ? println("less") : println("more")

more


In [214]:
xx = 1000
yy = 10
xx < 100 ? print("cool") : yy < 100 ? println("y no good") : println("y good")

y no good


In [120]:
# 'outer' constructors
struct Circle
    radius::Float64
end

# Outer constructor
Circle(diameter::Float64, is_diameter::Bool) = is_diameter ? Circle(diameter / 2) : Circle(diameter)

Circle

In [215]:
println( Circle(10.0,true) )
println( Circle(10.0,false) )

Circle(5.0)
Circle(10.0)


In [122]:
#inner and outer constructors
struct Circle2
    radius::Float64
    Circle2(radius) = new(radius)
end

# Outer constructor
Circle(diameter::Float64, is_diameter::Bool) = is_diameter ? Circle(diameter / 2) : Circle(diameter)

Circle

In [123]:
println( Circle(10.0,true) )
println( Circle(10.0) )

Circle(5.0)
Circle(10.0)


In [124]:
# define an abstract type and then create structs that are subtypes of that abstract type
abstract type Shape end

struct Square <: Shape
    side::Float64
end

struct Triangle <: Shape
    base::Float64
    height::Float64
end

In [125]:
# Define a function that calculates the area of any shape
function area(shape::Shape)
    if shape isa Square
        return shape.side^2
    elseif shape isa Triangle
        return 0.5 * shape.base * shape.height
    else
        throw(ArgumentError("Unsupported shape"))
    end
end

sq = Square(5.0)
tri = Triangle(3.0, 4.0)
# Now you can calculate the area of any shape

println(area(sq)) 
println(area(tri))

25.0
6.0


In [126]:
# Structs can have fields of different types, including other structs.
struct Point8
    x::Float64
    y::Float64
end

# Define the Line struct
struct Line8
    start::Point8
    last::Point8
end

# Construct instances
start_point = Point8(1.0, 2.0)  
end_point = Point8(3.0, 4.0) 

my_line = Line8(start_point, end_point)  # Creates a Line from start_point to end_point

Line8(Point8(1.0, 2.0), Point8(3.0, 4.0))

In [127]:
# function and input argument checks based on type checks
#and type checks on custom types
struct Rectangle
    length::Float64
    width::Float64
end

area(r::Rectangle) = r.length * r.width

area (generic function with 2 methods)

In [128]:
rect1 = Rectangle(5,2)
area(rect1)

10.0

In [219]:
#Union types
x3a::Union{Int, Float64} = 10  # x can be either an Int or a Float64

10

In [220]:
#ok
x3a = x3a*10
println(x3a)
#ok
x3a = x3a/3
println(x3a)
#not ok
x3a = "hi"
println(x3a)

100
33.333333333333336


LoadError: MethodError: Cannot `convert` an object of type 
  String to an object of type 
  Union{Float64, Int64}
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [132]:
# Define a type alias
const myType = Union{Int, Float64, Char}

Union{Char, Float64, Int64}

In [133]:
x3::myType = 123

123

In [134]:
#ok
x3 = 123/2
println(x3)
#ok
x3 = 'd'
println(x3)
#not ok
x3 = "hi"
println(x3)

61.5
d


LoadError: MethodError: Cannot `convert` an object of type 
  String to an object of type 
  Union{Char, Float64, Int64}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

In [135]:
struct Box1
    contents::String
end
struct Box2
    label::String
end
struct Box3 
    weight::Float64
end

In [136]:
# Define a type alias on custom types
const boxTypeNumber = Union{Box1,Box2}

boxTypeNumber (alias for Union{Box1, Box2})

In [137]:
xBox::boxTypeNumber = Box1("present")

Box1("present")

In [138]:
xBox = Box2("utensils")

Box2("utensils")

In [139]:
#won't work
xBox = Box3(3.3)

LoadError: MethodError: Cannot `convert` an object of type 
  Box3 to an object of type 
  boxTypeNumber
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

## making arrays, matrices, tuples etc

In [140]:
arr1 = [1, 2, 3, 4]  # 1D array (Vector)
display(arr1)
arr2 = [1 2; 3 4]    # 2D array (Matrix)
display(arr2)

4-element Vector{Int64}:
 1
 2
 3
 4

2×2 Matrix{Int64}:
 1  2
 3  4

In [141]:
zeros_arr = zeros(3)
println(zeros_arr)
ones_arr = ones(3)
println(ones_arr)

[0.0, 0.0, 0.0]
[1.0, 1.0, 1.0]


In [142]:
rand_arr = rand(3)
println(rand_arr)

[0.16418764882153503, 0.9366339792710662, 0.6474277958073591]


In [143]:
range_arr1 = 1:5
println(range_arr1)

1:5


In [144]:
range_arr_collected = collect( 1:5 )
println( range_arr_collected )
lin_space = range(1, stop=5, length=5)  # [1.0, 2.0, 3.0, 4.0, 5.0]
println( lin_space)

[1, 2, 3, 4, 5]
1.0:1.0:5.0


In [146]:
# pre-allocated Arrays
empty_arr = Array{Int}(undef, 3)  # Uninitialized array
println( empty_arr )

[140594984305712, 140594984305728, 140595009347824]


In [151]:
vec = Array{Int}(undef, 5)  # Creates a 1D array of Ints with 5 elements
println("Before: ", vec)
vec .= 1:5  # Filling in the array
println("After: ", vec)

Before: [140594961227728, 5416, -1, 0, 140594990844336]
After: [1, 2, 3, 4, 5]


In [231]:
mat = Array{Float64}(undef, 3, 2)  
display( mat)
mat .= [1.1 2.2; 3.3 4.4; 5.5 6.6] 
display( mat)

3×2 Matrix{Float64}:
 0.0           0.0
 6.9463e-310   6.9463e-310
 6.94631e-310  6.9463e-310

3×2 Matrix{Float64}:
 1.1  2.2
 3.3  4.4
 5.5  6.6

In [232]:
mat = ones(3,4)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [233]:
mat[1,:] .= 2
mat[2:end,1] .= 4
mat

3×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 4.0  1.0  1.0  1.0
 4.0  1.0  1.0  1.0

In [236]:
mat[2:5] .= rand(4)
mat

3×4 Matrix{Float64}:
 2.0       0.512216  2.0  2.0
 0.161202  0.384358  1.0  1.0
 0.526264  1.0       1.0  1.0

In [237]:
length(mat)

12

In [239]:
arr_3d = Array{String}(undef, 2, 2, 2)  # a 2x2x2 3D array of Strings
println("Before:\n", arr_3d)


Before:
[#undef #undef; #undef #undef;;; #undef #undef; #undef #undef]


In [154]:
struct PointX
    x::Float64
    y::Float64
end

points = Array{PointX}(undef, 2)  # Creates an array of 2 Points
println("Before: ", points)
points .= [PointX(1.0, 2.0), PointX(3.0, 4.0)]  # Filling in the array
println("After: ", points)

Before: PointX[PointX(6.9462340451923e-310, 6.94630483329594e-310), PointX(6.9463051160185e-310, 6.94630483329594e-310)]
After: PointX[PointX(1.0, 2.0), PointX(3.0, 4.0)]


In [149]:
arr_vcat = vcat([1, 2], [3, 4])  # Vertical concatenation: [1, 2, 3, 4]
println( arr_vcat )
arr_hcat = hcat([1, 2], [3, 4])  # Horizontal concatenation: [1 3; 2 4]
display( arr_hcat )

[1, 2, 3, 4]


2×2 Matrix{Int64}:
 1  3
 2  4

In [148]:
three_d_arr = rand(2, 2, 2)  # 3D array with random values
display(three_d_arr)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.509968  0.63164
 0.100091  0.540134

[:, :, 2] =
 0.221921  0.276734
 0.675157  0.20821

In [150]:
reshaped_arr = reshape(1:4, (2, 2))  # [1 3; 2 4]
display( reshaped_arr )

2×2 reshape(::UnitRange{Int64}, 2, 2) with eltype Int64:
 1  3
 2  4

In [127]:
for i in 1:5
    print("i = $i");print("\n")
end

i = 1
i = 2
i = 3
i = 4
i = 5


In [137]:
range(-1.2, stop=22, step=4.3)

-1.2:4.3:20.3

In [138]:
arr = [1, 2, 3, 4, 5]
for x in range(-1.2, stop=22, step=4.3)
    println(x)
end

-1.2
3.1
7.4
11.7
16.0
20.3


In [139]:
arr = ["a", "b", "c"]
for (index, value) in enumerate(arr)
    println("Index: $index, Value: $value")
end


Index: 1, Value: a
Index: 2, Value: b
Index: 3, Value: c


In [140]:
for i in 1:3
    for j in 4:6
        println((i,j))
    end
end

(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)


In [141]:
for i in 1:3, j in 4:6
    println((i, j))
end


(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)


In [142]:
for i in 1:3, j in 4:6, k in 7:8
    println((i, j,k))
end

(1, 4, 7)
(1, 4, 8)
(1, 5, 7)
(1, 5, 8)
(1, 6, 7)
(1, 6, 8)
(2, 4, 7)
(2, 4, 8)
(2, 5, 7)
(2, 5, 8)
(2, 6, 7)
(2, 6, 8)
(3, 4, 7)
(3, 4, 8)
(3, 5, 7)
(3, 5, 8)
(3, 6, 7)
(3, 6, 8)


In [143]:
dict = Dict("a" => 1, "b" => 2, "c" => [1,2,4], 12 => 'c')

Dict{Any, Any} with 4 entries:
  "c" => [1, 2, 4]
  "b" => 2
  12  => 'c'
  "a" => 1

In [146]:
dict["c"]

3-element Vector{Int64}:
 1
 2
 4

In [147]:
dict = Dict("a" => 1, "b" => 2)
for (key, value) in dict
    println("Key: $key, Value: $value")
end


Key: b, Value: 2
Key: a, Value: 1


In [148]:
arr = [1, 2, 3, 4, 5]
deleteat!(arr, 3) 

4-element Vector{Int64}:
 1
 2
 4
 5

f1 (generic function with 1 method)

In [162]:
filter!( x-> x >=10 , collect(1:20))

11-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [150]:
arr = [1, 2, 3, 4, 5]
filter!(x -> x != 3, arr)

4-element Vector{Int64}:
 1
 2
 4
 5

In [170]:
arr = [1, 2, 3]
push!(arr, 3,4,5) 

6-element Vector{Int64}:
 1
 2
 3
 3
 4
 5

In [172]:
[ [1,2,3]..., [2,3,4]...]

6-element Vector{Int64}:
 1
 2
 3
 2
 3
 4

In [179]:
arr = [1, 2, 4]
insert!(arr, 2, 22)

4-element Vector{Int64}:
  1
 22
  2
  4

In [180]:
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
append!(arr1, arr2) 

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [182]:
arr1

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [54]:
#nested array
result = [i * j for i in 1:3 for j in 1:3]

9-element Vector{Int64}:
 1
 2
 3
 2
 4
 6
 3
 6
 9

In [185]:
# include a comma to make into a matrix
matrix_result = [i * j for i in 1:3, j in 1:3, k in 1:2]


3×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 2  4  6
 3  6  9

[:, :, 2] =
 1  2  3
 2  4  6
 3  6  9

In [189]:
even_result = [i * j for i in 1:3 for j in 1:3 if (i * j) % 2 == 0]


5-element Vector{Int64}:
 2
 2
 4
 6
 6