In [1]:
# commented line is commented, all text here is ignored by Julia

In [2]:
#=
multiple
commented 
lines
=#

#=multiple
commented 
lines=#

In [3]:
#mandatory new language greeting
print("Hello World!")

Hello World!

In [4]:
#variable assignment 
x = 10

10

In [5]:
#reassignment
x = 100
println(x)

100


In [6]:
#make it a constant
const y = 1000

1000

In [7]:
#attempt to reassign it, it does not produce an 'error' but produces a 'warning'
#still mutable
y = 1

1

In [8]:
#still reassigns though
println(y)

1


In [9]:
#'string interpolation', we can put variables inside strings 
println("y = $(y)")

y = 1


In [10]:
#we can do computations inside the parenthesis of the string interpolation
println("y = $(y+1)")

y = 2


In [11]:
#we can omit the parenthesis when the variable does not include any operations on it before printing
println("y = $y")

y = 1


In [12]:
# multiple interpolation and operations including strings
x1 = 10
y1 = 20
str1 = "cat"
println("x1=$x1, y1+x1=$(y1 + x1), string data = $str1")

x1=10, y1+x1=30, string data = cat


In [13]:
#when can print without a new line being included
print("no new line: 1, ")
print("no new line: 2, ")
println("new line after this: 3")
print("on new line: 4")

no new line: 1, no new line: 2, new line after this: 3
on new line: 4

In [14]:
#new lines can be produced manually by inserting a 'special character' within the string that is: \n 
print("a new lines after this\n")
print("no new line 1, ")
print("no new line 2, ")
print("new line after this \n")
print("now new line 3")

a new lines after this
no new line 1, no new line 2, new line after this 
now new line 3

In [15]:
#assign mutliple variables at once
a,b,c = 20, 40, 60
println(a)
println(b)
println(c)

20
40
60


In [16]:
#standard aritmetic
t_0 = 10
#addition
t_1 = t_0 + 1

11

In [17]:
#print a descriptive string and the value
println("t_0 + 1 = ", t_1)
#subtraction
t_2 = t_0 - t_1
println( t_2 )

t_0 + 1 = 11
-1


In [18]:
#multiplication
println("multiplication of t_2 * 10 = $( t_2*10 )")

multiplication of t_2 * 10 = -10


In [19]:
#exponentiation
t_3 = t_0 ^ 2
println("t_3 = t_0 ^ 2 = $(t_3)")

t_3 = t_0 ^ 2 = 100


In [20]:
#division
t_4 = t_0 / 2
println("t_4 = t_0 / 2 = $(t_4)")

t_4 = t_0 / 2 = 5.0


In [21]:
# division
t_5 = t_0 / 3

3.3333333333333335

In [ ]:
# make fractions, the double forward slash, // , stops julia from making decimal numbers
t_6 = t_0 // 3

In [ ]:
# add fractions together
t_7 = (t_0 // 3) + (7 // 4)

In [ ]:
# putting a semicolon at the end of a statement keeps it from printing by default the result of the last statement
10 * 3;

In [25]:
#we can put multiple statements on the same line if we put semicolons between them
x = 5; x2 = x^2; x2 = x2 // 7; print(x2)

25//7

## Strings

In [26]:
# strings
s1 = "Howdy!"
println(s1)

Howdy!


In [27]:
# we can do string interpolation with a string
println("s1 = $(s1)")

s1 = Howdy!


In [28]:
# concatenate strings with the asterix, with numbers it is a multiplication and with strings it puts them together
s2 = s1 * " How are you?"

"Howdy! How are you?"

In [29]:
# length of a string
s2_length = length(s2)
println("length of s2 = $(s2_length)")

length of s2 = 19


In [30]:
# subset of the string (treat like an array) to get a selected range of characters
s3 = s2[1:12]

"Howdy! How a"

In [31]:
s4 = s2[5:12]

"y! How a"

In [32]:
#for arrays there is a keyword 'end' to get the last index
s2[5:end]

"y! How are you?"

In [33]:
#get a non-consequetive set of the characters as a string returned
s2[[1,3,5]]

"Hwy"

In [34]:
#combine individual indices (positions) in the array with the operation of ... called 'splat' to expand the range into the array
s2[[1,3,7:11...]]

"Hw How "

In [35]:
#use the end keyword to get the remaining characters of the string
s2[[1,3,7:end...]]

"Hw How are you?"

In [36]:
#by reassigning a string to a subset of itself
s2_orig = s2
s2 = s2[1:3] * s2[6:end]
s2

"How! How are you?"

In [37]:
#bring back the original value
s2 = s2_orig

"Howdy! How are you?"

In [38]:
#replace parts of a string with another string with the 'replace' function, it uses the operation of producing a 'pair' with =>
s7 = replace(s2, "Howdy" => "Hiya pal")
s7

"Hiya pal! How are you?"

In [39]:
# multiple substring replace using the pairs operator '=>'
s7 = replace(s2, "Howdy" => "Hiya", "How" => "What")

"Hiya! What are you?"

In [40]:
# multiple substring replace using the pairs operator '=>' of an array of pairs that have to be expanded with splat
s7 = replace(s2, ["Howdy" => "Hiya", "How" => "What"]...)

"Hiya! What are you?"

In [41]:
#we can construct a string using the string function
s8 = string(s7, "  Are you good?")

"Hiya! What are you?  Are you good?"

## characters

In [42]:
#build up a string from characters
c1 = 'H'
c2 = 'i'
c_str = string(c1,c2)
println("c_str = ",c_str)

c_str = Hi


In [43]:
string( 'c' + 100, 'c' + 200)

"Çī"

In [44]:
Char(Int('c')+87)

'º': Unicode U+00BA (category Lo: Letter, other)

In [45]:
Char.([55,123,43,444])

4-element Vector{Char}:
 '7': ASCII/Unicode U+0037 (category Nd: Number, decimal digit)
 '{': ASCII/Unicode U+007B (category Ps: Punctuation, open)
 '+': ASCII/Unicode U+002B (category Sm: Symbol, math)
 'Ƽ': Unicode U+01BC (category Lu: Letter, uppercase)

In [153]:
#UTF-8 encoding
δ = 1.23
print( δ * 10 )

12.3

In [154]:
#there are some built in constants
pi

π = 3.1415926535897...

In [157]:
#built in methods of constants
exp(1)

2.718281828459045

In [159]:
#variable names must begin with a letter [A-Z,a-z] or an underscore, or Unicode greater than 00A0, 
#Unicode character categories Lu/Ll/Lt/Lm/Lo/Nl (letters), Sc/So (currency and other symbols), and 
# a few other letter-like characters (e.g. a subset of the Sm math symbols) are allowed
# Subsequent characters may also include ! and digits (0-9 and other characters in categories Nd/No), 
# as well as other Unicode code points: diacritics and other modifying marks (categories Mn/Mc/Me/Sk), 
# some punctuation connectors (category Pc), primes, and a few other characters.

In [164]:
#an underscore '_' can be used to discard values
a,_,c = (1,2,3)

(1, 2, 3)

In [165]:
a

1

In [166]:
c

3

In [167]:
# you cannot use keywords like 'if' 'else' etc as variable names

## chaining expressions
var1 = var2 = var3

this can be generalized by saying: `variable = value` 

each value is computed on the right hand side. The whole assignment is considered as an expression equal to the right hand side `value`. 

In [168]:
a = b = c = 10
println("a = $a")
println("b = $b")
println("c = $c")

a = 10
b = 10
c = 10


In [169]:
a = b = (c = 10) * 2
println("a = $a")
println("b = $b")
println("c = $c")

a = 20
b = 20
c = 10


In [171]:
a = (b = (c = 10) * 2) / 4
println("a = $a")
println("b = $b")
println("c = $c")

a = 5.0
b = 20
c = 10


In [46]:
#specify the types at declaration 
q::Int = 10
r::Int64 = 20
s::Float64 = 3.14
t::String = "Hi!"
u = "Hey"
f::UInt8 = 4

4

In [47]:
#get the type of 'q'
typeof(q)

Int64

In [48]:
#check the type of 'q' against another
isa(q,Int)

true

In [49]:
#check the type of 'q' against another 'sibling' of Number
isa(q,Float64)

false

In [50]:
#check the type of 'q' against another parent type
isa(q,Number)

true

In [51]:
#check against the wrong type
q::String

LoadError: TypeError: in typeassert, expected String, got a value of type Int64

In [52]:
#check against the parent type as an assertion
q::Number

10

In [53]:
f = 55

55

In [54]:
f = -3

LoadError: InexactError: trunc(UInt8, -3)

In [55]:
z::Int32 = 1
println(typeof(x),", ", typeof(z) <: Number) 
println(typeof(x),", ", typeof(z) <: Int32)
println(typeof(x),", ", typeof(z) <: Int64)
println(typeof(x),", ", typeof(z) <: Int8)
println(typeof(x),", ", typeof(z) <: Char) 
println(typeof(x),", ", typeof(z) <: Real) 

Int64, true
Int64, true
Int64, false
Int64, false
Int64, false
Int64, true


In [56]:
#convert types
z_float = Float16(z)

Float16(1.0)

In [57]:
typeof(z_float)

Float16

In [58]:
#typecasting for compatibility in operations
a1::Float16 = 2
a2::Float64 = 3
b1::Int8 = 4
a4 = a1+a2+b1
typeof(a4)

Float64

In [59]:
#custom types
#immutable structs, the fields cannot be modified after defining them
struct Point
    x::Float64
    y::Float64
end

In [60]:
p1 = Point(1,2)

Point(1.0, 2.0)

In [61]:
println("x = ", p1.x," y = ",p1.y)

x = 1.0 y = 2.0


In [62]:
#try to change the values
p1.x = 3

LoadError: setfield!: immutable struct of type Point cannot be changed

In [63]:
#now we can define a mutable struct which allows modifying the values
mutable struct MutablePoint
    x::Float64
    y::Float64
end

In [64]:
mp = MutablePoint(1.0, 2.0)
mp.x = 3.0 

3.0

In [65]:
#we don't have to define types
mutable struct Names
    first
    last
end

In [66]:
nms = Names("alex","manz")

Names("alex", "manz")

In [67]:
#we can put commas and semicolons if we wish but must be consistent
mutable struct NamesA
    first,
    last
end
mutable struct NamesB2
    first
    last
end

In [68]:
mutable struct NamesC
    first; last; phone
end

In [69]:
mutable struct NamesE
    first; last; phone
end

In [70]:
#we can make 'parametric types(structs)' they are akin to Generics
struct parametricUser{T}
    userID::T
    userName
end

In [71]:
pu1 = parametricUser( Float16(123), "John" )

parametricUser{Float16}(Float16(123.0), "John")

In [72]:
println( pu1.userID )
println( typeof(pu1.userID) )

123.0
Float16


In [73]:
pu1 = parametricUser( 'z', "John" )

parametricUser{Char}('z', "John")

In [74]:
#we can make 'parametric types(structs)' with multiple parametric types and constrainst
struct parametricUserB{T1,T2<:Int,T3<:String}
    userID::T1
    count::T2
    userName::T3
    appID::T1
end

In [75]:
# ok
parametricUserB(123,2,"John",21)

parametricUserB{Int64, Int64, String}(123, 2, "John", 21)

In [76]:
# not ok, violates type constraint T3
parametricUserB(123,2,0,21)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[74]:3

In [77]:
# not ok, violates type constraint T2
parametricUserB(123,1.2,"John",21)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Float64, ::String, ::Int64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[74]:3

In [78]:
# not ok, violates type constraint for 'userID' and 'appID' to be the same
parametricUserB(123,12,"John",1.2)

LoadError: MethodError: no method matching parametricUserB(::Int64, ::Int64, ::String, ::Float64)
Closest candidates are:
  parametricUserB(::T1, ::T2, ::T3, ::T1) where {T1, T2<:Int64, T3<:String} at In[74]:3

In [79]:
# inner constructor
struct PositivePoint
    x::Float64
    y::Float64
    PositivePoint(x, y) = x > 0 && y > 0 ? new(x, y) : throw(ArgumentError("Coordinates must be positive"))
end

In [80]:
pp1 = PositivePoint(2,3.3)

PositivePoint(2.0, 3.3)

In [81]:
pp2 = PositivePoint(2,-3.3)

LoadError: ArgumentError: Coordinates must be positive

In [82]:
# different inner constructors
# Inner constructors are defined 
# inside the struct block and can enforce invariants or provide default values
struct PersonType2
    firstName
    lastName
    PersonType2(firstName,lastName) = new(firstName,lastName)
    PersonType2() = new("John","Doe")
end

In [83]:
pt2a = PersonType2()
println(pt2a)
pt2b = PersonType2("Bob","Minton")
println(pt2b)

PersonType2("John", "Doe")
PersonType2("Bob", "Minton")


In [84]:
#let us add optional arguments as well to simplify and expand to more use cases
struct PersonType3
    firstName
    lastName
    function PersonType3(firstName="John", lastName="Doe")
        new(firstName,lastName)
    end
end

In [85]:
pt3a = PersonType3()
println(pt3a)
pt3b = PersonType3("Bob")
println(pt3b)

PersonType3("John", "Doe")
PersonType3("Bob", "Doe")


In [86]:
# fails
pt3c = PersonType3(lastname="Minton")
println(pt3c)

LoadError: MethodError: no method matching PersonType3(; lastname="Minton")
Closest candidates are:
  PersonType3() at In[84]:5 got unsupported keyword argument "lastname"
  PersonType3(::Any) at In[84]:5 got unsupported keyword argument "lastname"
  PersonType3(::Any, ::Any) at In[84]:5 got unsupported keyword argument "lastname"

In [87]:
#adding for keyword arguments
struct PersonType4z
    id
    firstName
    lastName
    function PersonType4z(id;firstName="John", lastName="Doe") #added a semicolon
        new(id,firstName,lastName)
    end
end

In [88]:
pt4a = PersonType4z(1)
println(pt4a)
PersonType4z(2,lastName="baker",firstName="bob")

PersonType4z(1, "John", "Doe")


PersonType4z(2, "bob", "baker")

In [89]:
# inner constructor and keyword arguments
struct PersonType6
    firstName
    lastName
    function PersonType6(;firstName=nothing, lastName=nothing)
        # Check if firstName was provided
        if firstName === nothing
            println("firstName was not provided, using default.")
            firstName = "John"
        end

        # Check if lastName was provided
        if lastName === nothing
            println("lastName was not provided, using default.")
            lastName = "Doe"
        end

        return new(firstName, lastName)
    end
end

In [90]:
pt6a = PersonType6()
println(pt6a)
pt6c = PersonType6(lastName="Minton")
println(pt6c)
pt6d = PersonType6(firstName="Bob")
println(pt6d)
pt6e = PersonType6(firstName="Bob",lastName="Minton")
println(pt6e)

firstName was not provided, using default.
lastName was not provided, using default.
PersonType6("John", "Doe")
firstName was not provided, using default.
PersonType6("John", "Minton")
lastName was not provided, using default.
PersonType6("Bob", "Doe")
PersonType6("Bob", "Minton")


In [91]:
r = 1000
r < 100 ? println("less") : println("more")

more


In [92]:
xx = 1000
yy = 10
xx < 100 ? print("cool") : yy < 100 ? println("y no good") : println("y good")

y no good


In [93]:
# 'outer' constructors
struct Circle
    radius::Float64
end

# Outer constructor
Circle(diameter::Float64, is_diameter::Bool) = is_diameter ? Circle(diameter / 2) : Circle(diameter)

Circle

In [94]:
println( Circle(10.0,true) )
println( Circle(10.0,false) )

Circle(5.0)
Circle(10.0)


In [95]:
#inner and outer constructors
struct Circle2
    radius::Float64
    Circle2(radius) = new(radius)
end

# Outer constructor
Circle(diameter::Float64, is_diameter::Bool) = is_diameter ? Circle(diameter / 2) : Circle(diameter)

Circle

In [96]:
println( Circle(10.0,true) )
println( Circle(10.0) )

Circle(5.0)
Circle(10.0)


In [97]:
# define an abstract type and then create structs that are subtypes of that abstract type
abstract type Shape end

struct Square <: Shape
    side::Float64
end

struct Triangle <: Shape
    base::Float64
    height::Float64
end

In [98]:
# Define a function that calculates the area of any shape
function area(shape::Shape)
    if shape isa Square
        return shape.side^2
    elseif shape isa Triangle
        return 0.5 * shape.base * shape.height
    else
        throw(ArgumentError("Unsupported shape"))
    end
end

sq = Square(5.0)
tri = Triangle(3.0, 4.0)
# Now you can calculate the area of any shape

println(area(sq)) 
println(area(tri))

25.0
6.0


In [99]:
# Structs can have fields of different types, including other structs.
struct Point8
    x::Float64
    y::Float64
end

# Define the Line struct
struct Line8
    start::Point8
    last::Point8
end

# Construct instances
start_point = Point8(1.0, 2.0)  
end_point = Point8(3.0, 4.0) 

my_line = Line8(start_point, end_point)  # Creates a Line from start_point to end_point

Line8(Point8(1.0, 2.0), Point8(3.0, 4.0))

In [100]:
# function and input argument checks based on type checks
#and type checks on custom types
struct Rectangle
    length::Float64
    width::Float64
end

area(r::Rectangle) = r.length * r.width

area (generic function with 2 methods)

In [101]:
rect1 = Rectangle(5,2)
area(rect1)

10.0

In [102]:
#Union types
x3a::Union{Int, Float64} = 10  # x can be either an Int or a Float64

10

In [103]:
#ok
x3a = x3a*10
println(x3a)
#ok
x3a = x3a/3
println(x3a)
#not ok
x3a = "hi"
println(x3a)

100
33.333333333333336


LoadError: MethodError: Cannot `convert` an object of type 
  String to an object of type 
  Union{Float64, Int64}
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [104]:
# Define a type alias
const myType = Union{Int, Float64, Char}

Union{Char, Float64, Int64}

In [105]:
x3::myType = 123

123

In [106]:
#ok
x3 = 123/2
println(x3)
#ok
x3 = 'd'
println(x3)
#not ok
x3 = "hi"
println(x3)

61.5
d


LoadError: MethodError: Cannot `convert` an object of type 
  String to an object of type 
  Union{Char, Float64, Int64}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

In [107]:
struct Box1
    contents::String
end
struct Box2
    label::String
end
struct Box3 
    weight::Float64
end

In [108]:
# Define a type alias on custom types
const boxTypeNumber = Union{Box1,Box2}

boxTypeNumber (alias for Union{Box1, Box2})

In [109]:
xBox::boxTypeNumber = Box1("present")

Box1("present")

In [110]:
xBox = Box2("utensils")

Box2("utensils")

In [111]:
#won't work
xBox = Box3(3.3)

LoadError: MethodError: Cannot `convert` an object of type 
  Box3 to an object of type 
  boxTypeNumber
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

## making arrays, matrices, tuples etc

In [112]:
arr1 = [1, 2, 3, 4]  # 1D array (Vector)
display(arr1)
arr2 = [1 2; 3 4]    # 2D array (Matrix)
display(arr2)

4-element Vector{Int64}:
 1
 2
 3
 4

2×2 Matrix{Int64}:
 1  2
 3  4

In [113]:
zeros_arr = zeros(3)
println(zeros_arr)
ones_arr = ones(3)
println(ones_arr)

[0.0, 0.0, 0.0]
[1.0, 1.0, 1.0]


In [114]:
rand_arr = rand(3)
println(rand_arr)

[0.0019797818391125155, 0.5277790886343634, 0.9730327733914651]


In [115]:
range_arr1 = 1:5
println(range_arr1)

1:5


In [116]:
range_arr_collected = collect( 1:5 )
println( range_arr_collected )
lin_space = range(1, stop=5, length=5)  # [1.0, 2.0, 3.0, 4.0, 5.0]
println( lin_space)

[1, 2, 3, 4, 5]
1.0:1.0:5.0


In [117]:
# pre-allocated Arrays
empty_arr = Array{Int}(undef, 3)  # Uninitialized array
println( empty_arr )

[140601639443824, 140601618467056, 0]


In [118]:
vec = Array{Int}(undef, 5)  # Creates a 1D array of Ints with 5 elements
println("Before: ", vec)
vec .= 1:5  # Filling in the array
println("After: ", vec)

Before: [1, 1, 1, 1, 0]
After: [1, 2, 3, 4, 5]


In [119]:
mat = Array{Float64}(undef, 3, 2)  
display( mat)
mat .= [1.1 2.2; 3.3 4.4; 5.5 6.6] 
display( mat)

3×2 Matrix{Float64}:
 2.0e-323  4.0e-323
 1.5e-323  1.0e-323
 4.4e-323  5.0e-324

3×2 Matrix{Float64}:
 1.1  2.2
 3.3  4.4
 5.5  6.6

In [120]:
mat = ones(3,4)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [121]:
mat[1,:] .= 2
mat[2:end,1] .= 4
mat

3×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 4.0  1.0  1.0  1.0
 4.0  1.0  1.0  1.0

In [122]:
mat[2:5] .= rand(4)
mat

3×4 Matrix{Float64}:
 2.0        0.515845   2.0  2.0
 0.0200884  0.0403422  1.0  1.0
 0.0581858  1.0        1.0  1.0

In [123]:
length(mat)

12

In [124]:
arr_3d = Array{String}(undef, 2, 2, 2)  # a 2x2x2 3D array of Strings
println("Before:\n", arr_3d)


Before:
[#undef #undef; #undef #undef;;; #undef #undef; #undef #undef]


In [125]:
struct PointX
    x::Float64
    y::Float64
end

points = Array{PointX}(undef, 2)  # Creates an array of 2 Points
println("Before: ", points)
points .= [PointX(1.0, 2.0), PointX(3.0, 4.0)]  # Filling in the array
println("After: ", points)

Before: PointX[PointX(6.9466446741947e-310, 6.9466446741979e-310), PointX(6.94664467420104e-310, 6.9466446742042e-310)]
After: PointX[PointX(1.0, 2.0), PointX(3.0, 4.0)]


In [126]:
arr_vcat = vcat([1, 2], [3, 4])  # Vertical concatenation: [1, 2, 3, 4]
println( arr_vcat )
arr_hcat = hcat([1, 2], [3, 4])  # Horizontal concatenation: [1 3; 2 4]
display( arr_hcat )

[1, 2, 3, 4]


2×2 Matrix{Int64}:
 1  3
 2  4

In [127]:
three_d_arr = rand(2, 2, 2)  # 3D array with random values
display(three_d_arr)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.23742   0.323226
 0.711056  0.890593

[:, :, 2] =
 0.685553  0.387369
 0.629589  0.664728

In [128]:
reshaped_arr = reshape(1:4, (2, 2))  # [1 3; 2 4]
display( reshaped_arr )

2×2 reshape(::UnitRange{Int64}, 2, 2) with eltype Int64:
 1  3
 2  4

## mutating and reassigning arrays

When dealing with primitives like integers or single values if we reassign variable names to values, even if they we set referring to each other the reassignment points them to a new 'object' or 'value'

In [1]:
a = 5
b = a
a = 10
println("a = $a, b = $b")

a = 10, b = 5


### mutating the arrays means that the object variable names point to has changed and the changes can be picked up from any of the variable names still pointing to the same 'value' (array, struct, etc)

In [2]:
arr_1 = [1,2,3]
arr_2 = arr_1
arr_3 = arr_2

#changing a value in arr_1 changes it for all variable names 
#pointing to the array itself and if a variable name changes
#what it is pointing to the rest are unaffected

arr_1[1] = 11
arr_3[3] = 33
arr_1 = "hello"

println("arr_1 = $arr_1, arr_2 = $arr_2, arr_3 = $arr_3")

arr_1 = hello, arr_2 = [11, 2, 33], arr_3 = [11, 2, 33]


### when we pass a set of arguments to a function some will change the original values and other will not

when we pass in primitive values the originals are not changed but when we pass in an object like an array they are changed

Here we see a function that does 'reassignment of the variable name' but not mutation

In [5]:
function fn_nonmutating(x,y,z)
    x = 10
    y = [11,12,13]
    z = 12
    return [x,y,z]
end

v1 = [1,2,3]
v2 = [1,2,3]
v3 = [1,2,3]

println( "calling fn_nonmutating values before" )
println( "v1 = $v1" )
println( "v2 = $v2" )
println( "v3 = $v3" )

println( "values returned from $(fn_nonmutating(v1,v2,v3))" )

println( "calling fn_nonmutating values after" )
println( "v1 = $v1" )
println( "v2 = $v2" )
println( "v3 = $v3" )

calling fn_nonmutating values before
v1 = [1, 2, 3]
v2 = [1, 2, 3]
v3 = [1, 2, 3]
values returned from Any[10, [11, 12, 13], 12]
calling fn_nonmutating values after
v1 = [1, 2, 3]
v2 = [1, 2, 3]
v3 = [1, 2, 3]


Here we do not just reassign but also mutation which affects the original variables after the call. In Julia such functions that mutate have an exclamation mark to note that they mutate

In [7]:
function fn_mutating!(x,y,z)
    x = 10
    y[1] = 11
    z[3] = 12
    return [x,y,z]
end

v1 = [1,2,3]
v2 = [1,2,3]
v3 = [1,2,3]

println( "calling fn_mutating! values before" )
println( "v1 = $v1" )
println( "v2 = $v2" )
println( "v3 = $v3" )

println( "values returned from $(fn_mutating!(v1,v2,v3))" )

println( "calling fn_mutating! values after" )
println( "v1 = $v1" )
println( "v2 = $v2" )
println( "v3 = $v3" )

calling fn_mutating! values before
v1 = [1, 2, 3]
v2 = [1, 2, 3]
v3 = [1, 2, 3]
values returned from Any[10, [11, 2, 3], [1, 2, 12]]
calling fn_mutating! values after
v1 = [1, 2, 3]
v2 = [11, 2, 3]
v3 = [1, 2, 12]


In [129]:
for i in 1:5
    print("i = $i");print("\n")
end

i = 1
i = 2
i = 3
i = 4
i = 5


In [130]:
range(-1.2, stop=22, step=4.3)

-1.2:4.3:20.3

In [131]:
arr = [1, 2, 3, 4, 5]
for x in range(-1.2, stop=22, step=4.3)
    println(x)
end

-1.2
3.1
7.4
11.7
16.0
20.3


In [132]:
arr = ["a", "b", "c"]
for (index, value) in enumerate(arr)
    println("Index: $index, Value: $value")
end


Index: 1, Value: a
Index: 2, Value: b
Index: 3, Value: c


In [133]:
for i in 1:3
    for j in 4:6
        println((i,j))
    end
end

(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)


In [134]:
for i in 1:3, j in 4:6
    println((i, j))
end


(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)


In [135]:
for i in 1:3, j in 4:6, k in 7:8
    println((i, j,k))
end

(1, 4, 7)
(1, 4, 8)
(1, 5, 7)
(1, 5, 8)
(1, 6, 7)
(1, 6, 8)
(2, 4, 7)
(2, 4, 8)
(2, 5, 7)
(2, 5, 8)
(2, 6, 7)
(2, 6, 8)
(3, 4, 7)
(3, 4, 8)
(3, 5, 7)
(3, 5, 8)
(3, 6, 7)
(3, 6, 8)


In [136]:
dict = Dict("a" => 1, "b" => 2, "c" => [1,2,4], 12 => 'c')

Dict{Any, Any} with 4 entries:
  "c" => [1, 2, 4]
  "b" => 2
  12  => 'c'
  "a" => 1

In [137]:
dict["c"]

3-element Vector{Int64}:
 1
 2
 4

In [138]:
dict = Dict("a" => 1, "b" => 2)
for (key, value) in dict
    println("Key: $key, Value: $value")
end


Key: b, Value: 2
Key: a, Value: 1


In [139]:
arr = [1, 2, 3, 4, 5]
deleteat!(arr, 3) 

4-element Vector{Int64}:
 1
 2
 4
 5

In [140]:
filter!( x-> x >=10 , collect(1:20))

11-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [141]:
arr = [1, 2, 3, 4, 5]
filter!(x -> x != 3, arr)

4-element Vector{Int64}:
 1
 2
 4
 5

In [142]:
arr = [1, 2, 3]
push!(arr, 3,4,5) 

6-element Vector{Int64}:
 1
 2
 3
 3
 4
 5

In [143]:
[ [1,2,3]..., [2,3,4]...]

6-element Vector{Int64}:
 1
 2
 3
 2
 3
 4

In [144]:
arr = [1, 2, 4]
insert!(arr, 2, 22)

4-element Vector{Int64}:
  1
 22
  2
  4

In [145]:
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
append!(arr1, arr2) 

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [146]:
arr1

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [147]:
#nested array
result = [i * j for i in 1:3 for j in 1:3]

9-element Vector{Int64}:
 1
 2
 3
 2
 4
 6
 3
 6
 9

In [148]:
# include a comma to make into a matrix
matrix_result = [i * j for i in 1:3, j in 1:3, k in 1:2]


3×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 2  4  6
 3  6  9

[:, :, 2] =
 1  2  3
 2  4  6
 3  6  9

In [149]:
even_result = [i * j for i in 1:3 for j in 1:3 if (i * j) % 2 == 0]


5-element Vector{Int64}:
 2
 2
 4
 6
 6

In [150]:
include("./test1.jl")

Simple_Return (generic function with 1 method)

In [151]:
val = Simple_Return()
println("Simple_Return function value = $val")

Simple_Return function value = 22


In [152]:
?repeat

search: repeat reshaped_arr



```
repeat(A::AbstractArray, counts::Integer...)
```

Construct an array by repeating array `A` a given number of times in each dimension, specified by `counts`.

See also: [`fill`](@ref), [`Iterators.repeated`](@ref), [`Iterators.cycle`](@ref).

# Examples

```jldoctest
julia> repeat([1, 2, 3], 2)
6-element Vector{Int64}:
 1
 2
 3
 1
 2
 3

julia> repeat([1, 2, 3], 2, 3)
6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3
```

---

```
repeat(A::AbstractArray; inner=ntuple(Returns(1), ndims(A)), outer=ntuple(Returns(1), ndims(A)))
```

Construct an array by repeating the entries of `A`. The i-th element of `inner` specifies the number of times that the individual entries of the i-th dimension of `A` should be repeated. The i-th element of `outer` specifies the number of times that a slice along the i-th dimension of `A` should be repeated. If `inner` or `outer` are omitted, no repetition is performed.

# Examples

```jldoctest
julia> repeat(1:2, inner=2)
4-element Vector{Int64}:
 1
 1
 2
 2

julia> repeat(1:2, outer=2)
4-element Vector{Int64}:
 1
 2
 1
 2

julia> repeat([1 2; 3 4], inner=(2, 1), outer=(1, 3))
4×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 3  4  3  4  3  4
 3  4  3  4  3  4
```

---

```
repeat(s::AbstractString, r::Integer)
```

Repeat a string `r` times. This can be written as `s^r`.

See also [`^`](@ref :^(::Union{AbstractString, AbstractChar}, ::Integer)).

# Examples

```jldoctest
julia> repeat("ha", 3)
"hahaha"
```

---

```
repeat(c::AbstractChar, r::Integer) -> String
```

Repeat a character `r` times. This can equivalently be accomplished by calling [`c^r`](@ref :^(::Union{AbstractString, AbstractChar}, ::Integer)).

# Examples

```jldoctest
julia> repeat('A', 3)
"AAA"
```
