### <span style="color:orange">Let's make a word cloud</span>

In [4]:
#import Pkg
#Pkg.add("WordCloud")
#Pkg.add("Languages")

In [1]:
using WordCloud, Languages

In [2]:
text1 = "Hello, my name is Alex, what is your name? How are you today? It is quite hot outside."
text1_words = split(text1," ")

18-element Vector{SubString{String}}:
 "Hello,"
 "my"
 "name"
 "is"
 "Alex,"
 "what"
 "is"
 "your"
 "name?"
 "How"
 "are"
 "you"
 "today?"
 "It"
 "is"
 "quite"
 "hot"
 "outside."

In [3]:
text1_words_unique = unique(text1_words)

16-element Vector{SubString{String}}:
 "Hello,"
 "my"
 "name"
 "is"
 "Alex,"
 "what"
 "your"
 "name?"
 "How"
 "are"
 "you"
 "today?"
 "It"
 "quite"
 "hot"
 "outside."

In [4]:
findall(text1_words_unique[1] .== text1_words)

1-element Vector{Int64}:
 1

In [5]:
findall(text1_words_unique[4] .== text1_words)

3-element Vector{Int64}:
  4
  7
 15

In [6]:
length( findall(text1_words_unique[4] .== text1_words) )

3

In [7]:
counts = map(ind -> length(findall(text1_words_unique[ind] .== text1_words)), 1:length(text1_words_unique))

16-element Vector{Int64}:
 1
 1
 1
 3
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [8]:
counts_norm = counts ./ sum(counts)

16-element Vector{Float64}:
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.16666666666666666
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555
 0.05555555555555555

In [9]:
word_weights = counts_norm;

In [10]:
run(`ls`)

alice.svg
animations
Audio
AutoEncoder
cloud1.svg
countryRoadNoStopWords.svg
countryRoad.svg
DataBase
DataScienceCaseStudies
eagle.png
figs
fileMapStuff
Flux
GANs
input.txt
Julia_Use_Other_Languages
lettermask.svg
Mongo
PCA
Plotting
plottingJL5.ipynb
plottingJL9-naivebayes.ipynb
plottingJLb11-JLflux.ipynb
plottingJLbFluxConv.ipynb
plottingJLbFlux.ipynb
plottingJLbFluxText.ipynb
README.md
Regression
runs
silhouette-bald-eagle.png
tl_2017_12_cousub
TransferLearning
united_states_florida_administrative_boundaries_polygon


Process(`ls`, ProcessExited(0))

In [11]:
wc = wordcloud(text1_words_unique, word_weights)
generate!(wc)
paint(wc, "cloud1.svg")

color scheme: :Set1_6, random size: 5, shuffled
angles = [0, 90]
shape(squircle, 131, 113, rt=1.533, color=0.0, padding=9)
fonts = "sans-serif Normal"
mask size: 131×149, content area: 95² (24²/word)
set fontsize ∈ [8.0, 131]
set density = 0.5
⋯scale=26.565073404754596, density=0.4949086682165394	↓
fontsize ∈ [11.867274118740122, 35.60182235622037]
▸1. scale = 26.701366767165272


[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 40(+21) η -> 0.177 (current 9 collisions, best 2 collisions)


46 epochs


In [12]:
#country road lyrics
text2 = "Almost heaven, West Virginia
Blue Ridge Mountains, Shenandoah River
Life is old there, older than the trees
Younger than the mountains, growin' like a breeze
Country roads, take me home
To the place I belong
West Virginia, mountain mama
Take me home, country roads
All my memories gather 'round her
Miner's lady, stranger to blue water
Dark and dusty, painted on the sky
Misty taste of moonshine, teardrop in my eye
Country roads, take me home
To the place I belong
West Virginia, mountain mama
Take me home, country roads
I hear her voice in the mornin' hour, she calls me
The radio reminds me of my home far away
Drivin' down the road, I get a feelin'
That I should've been home yesterday, yesterday
Country roads, take me home
To the place I belong
West Virginia, mountain mama
Take me home, country roads
Country roads, take me home
To the place I belong
West Virginia, mountain mama
Take me home, country roads
Take me home, (down) country roads
Take me home, (down) country roads"

"Almost heaven, West Virginia\nBlue Ridge Mountains, Shenandoah River\nLife is old there, older than the trees\nYounger than the mountains, growin' like a breeze\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nAll my" ⋯ 444 bytes ⋯ ", take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nTake me home, (down) country roads\nTake me home, (down) country roads"

In [13]:
text2_words = split(text2," ")
text2_words_unique = unique(text2_words)
counts = map(ind -> length(findall(text2_words_unique[ind] .== text2_words)),1:length(text2_words_unique))
counts_norm = counts ./ sum(counts)
word_weights = counts_norm;
wc = wordcloud(text2_words_unique, word_weights)
generate!(wc)
paint(wc, "countryRoad.svg")

color scheme: :tableau_orange_light, random size: 7, shuffled
angles = [0, 45, 90, -45]
shape(ellipse, 457, 293, color=(0.027, 0.055, 0.029), padding=32)
fonts = "華康儷宋 Std Light"
mask size: 357×521, content area: 323² (36²/word)
set fontsize ∈ [8.0, 357]
set density = 0.5
⋯scale=40.39705280091606, density=0.6068066792413087	↑
⋯scale=36.669881614582025, density=0.5309146615857453	↑
⋯scale=35.038152720848764, density=0.4992774049002806	↓
fontsize ∈ [8.0, 69.80723937292112]
59 words(74%) are limited to the minimum font size.


┌ Warning: It seems too crowded. Word size may be seriously distorted. You need to reduce the number of words or set a larger mask.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-method.jl:60


▸1. scale = 35.07626848774237


[ Info: nepoch: 1000, patient: 10


10 epochs


[ Info: @epoch 5(+2), 19(1) collisions, reposition [64] to [(542, 527)]


In [14]:
song = deepcopy(text2)

"Almost heaven, West Virginia\nBlue Ridge Mountains, Shenandoah River\nLife is old there, older than the trees\nYounger than the mountains, growin' like a breeze\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nAll my" ⋯ 444 bytes ⋯ ", take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nTake me home, (down) country roads\nTake me home, (down) country roads"

In [15]:
song_tmp = deepcopy(song)

"Almost heaven, West Virginia\nBlue Ridge Mountains, Shenandoah River\nLife is old there, older than the trees\nYounger than the mountains, growin' like a breeze\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nAll my" ⋯ 444 bytes ⋯ ", take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nCountry roads, take me home\nTo the place I belong\nWest Virginia, mountain mama\nTake me home, country roads\nTake me home, (down) country roads\nTake me home, (down) country roads"

In [16]:
print(stopwords(Languages.English()))

["a", "about", "above", "across", "after", "again", "against", "all", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "an", "and", "another", "any", "anybody", "anyone", "anything", "anywhere", "are", "area", "areas", "aren't", "around", "as", "ask", "asked", "asking", "asks", "at", "away", "b", "back", "backed", "backing", "backs", "be", "became", "because", "become", "becomes", "been", "before", "began", "behind", "being", "beings", "below", "best", "better", "between", "big", "both", "but", "by", "c", "came", "can", "cannot", "can't", "case", "cases", "certain", "certainly", "clear", "clearly", "come", "could", "couldn't", "d", "did", "didn't", "differ", "different", "differently", "do", "does", "doesn't", "doing", "done", "don't", "down", "downed", "downing", "downs", "during", "e", "each", "early", "either", "end", "ended", "ending", "ends", "enough", "even", "evenly", "ever", "every", "everybody", "everyone", "everything", "everywhere", "f", "f

In [17]:
song_splitted = split(song_tmp, (' ','_',',','.','\n'));
song_splitted;
length(song_splitted)

199

In [18]:
stop_words = stopwords(Languages.English())
inds_total = []
words_to_include = []

for ii in 1:length(song_splitted)
    #'in' is a keyword for membership of the left element in respect to the variable on the right
    ind_remove = song_splitted[ii] in stop_words
    if( ind_remove == true )
        print("ind $(ii) remove=$(song_splitted[ii]), ")
        append!(inds_total,ii)
    else
        append!(words_to_include,[song_splitted[ii]])
    end
    
    #ind_remove = findall( song_splitted .== "Ridge" )
    #deleteat!(song_splitted,ind_remove)
    
end
#song_splitted

ind 13 remove=is, ind 14 remove=old, ind 15 remove=there, ind 17 remove=older, ind 18 remove=than, ind 19 remove=the, ind 22 remove=than, ind 23 remove=the, ind 27 remove=like, ind 28 remove=a, ind 33 remove=take, ind 34 remove=me, ind 37 remove=the, ind 38 remove=place, ind 47 remove=me, ind 53 remove=my, ind 57 remove=her, ind 62 remove=to, ind 66 remove=and, ind 70 remove=on, ind 71 remove=the, ind 75 remove=of, ind 79 remove=in, ind 80 remove=my, ind 85 remove=take, ind 86 remove=me, ind 89 remove=the, ind 90 remove=place, ind 99 remove=me, ind 106 remove=her, ind 108 remove=in, ind 109 remove=the, ind 113 remove=she, ind 115 remove=me, ind 119 remove=me, ind 120 remove=of, ind 121 remove=my, ind 123 remove=far, ind 124 remove=away, ind 126 remove=down, ind 127 remove=the, ind 131 remove=get, ind 132 remove=a, ind 137 remove=been, ind 145 remove=take, ind 146 remove=me, ind 149 remove=the, ind 150 remove=place, ind 159 remove=me, ind 167 remove=take, ind 168 remove=me, ind 171 remo

In [19]:
inds_total

56-element Vector{Any}:
  13
  14
  15
  17
  18
  19
  22
  23
  27
  28
  33
  34
  37
   ⋮
 145
 146
 149
 150
 159
 167
 168
 171
 172
 181
 187
 194

In [20]:
words_to_include

143-element Vector{Any}:
 "Almost"
 "heaven"
 ""
 "West"
 "Virginia"
 "Blue"
 "Ridge"
 "Mountains"
 ""
 "Shenandoah"
 "River"
 "Life"
 ""
 ⋮
 "Take"
 "home"
 ""
 "(down)"
 "country"
 "roads"
 "Take"
 "home"
 ""
 "(down)"
 "country"
 "roads"

In [21]:
#word cloud, with no stop words this time.
text2_words_unique = unique(words_to_include)
counts = map(ind -> length(findall(text2_words_unique[ind] .== text2_words)),1:length(text2_words_unique))
counts_norm = counts ./ sum(counts)
word_weights = counts_norm;
wc = wordcloud(convert(Array{String,1},text2_words_unique), word_weights)
generate!(wc)
paint(wc, "countryRoadNoStopWords.svg")

color scheme: :Archambault, random size: 4, shuffled
angles = [30, -30]
backgroundcolor = :maskcolor
shape(ellipse, 522, 425, color=(0.931, 0.983, 0.907), padding=41)
fonts = "Courier Bold"
mask size: 507×604, content area: 416² (54²/word)
set fontsize ∈ [8.0, 507]
set density = 0.5
The word "country"(115.26907266973085) is too big. Set maxfontsize = 96.36458680120812.
⋯scale=60.597484145348496, density=0.3792684671793955	↓
⋯scale=69.5770846905522, density=0.45006438919692365	↓
The word "mountain"(95.4518950866368) is too big. Set maxfontsize = 84.58533715385141.
⋯scale=75.26925347610823, density=0.4598891074941871	↓
⋯scale=95.03454294794508, density=0.5764872115900556	↑
⋯scale=82.60407547142137, density=0.5031157216955822	↑
fontsize ∈ [8.0, 84.58533715385141]
33 words(56%) are limited to the minimum font size.


┌ Warning: Some words are limited to the maximum font size. Please set a `maxfontsize` in `wordcloud` or set a `maxweight` in `processtext`.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-method.jl:65


▸1. scale = 82.03453514954903


[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 73(+21) η -> 0.177 (current 26 collisions, best 16 collisions)
[ Info: @epoch 96(+21) η -> 0.125 (current 24 collisions, best 14 collisions)
[ Info: @epoch 154(+21) η -> 0.088 (current 22 collisions, best 10 collisions)
[ Info: @epoch 185(+4), 8(2) collisions, reposition [4] to [(426, 358)]
[ Info: @epoch 207(+21) η -> 0.063 (current 18 collisions, best 2 collisions)
[ Info: @epoch 235(+21) η <- 0.088 (collisions 10 ≥ 2)
[ Info: @epoch 251(+65), 18(2) collisions, reposition [4] to [(346, 534)]
[ Info: @epoch 251, random move [33, 4]
[ Info: @epoch 271(+21) η -> 0.063 (current 41 collisions, best 9 collisions)
[ Info: @epoch 298(+21) η <- 0.088 (collisions 24 ≥ 9)
[ Info: @epoch 345(+21) η <- 0.125 (collisions 19 ≥ 10)
[ Info: @epoch 395(+21) η -> 0.088 (current 17 collisions, best 12 collisions)
[ Info: @epoch 427(+21) η <- 0.125 (collisions 13 ≥ 12)
[ Info: @epoch 432(+58), 13(1) collisions, reposition [4] to [(362, 422)]
[ Info: @epoch

▸2. try scale = 79.57349909506256. The density is reduced to 0.48587551421928105
fontsize ∈ [8.0, 84.58533715385141]
33 words(56%) are limited to the minimum font size.


┌ Warning: Some words are limited to the maximum font size. Please set a `maxfontsize` in `wordcloud` or set a `maxweight` in `processtext`.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-method.jl:65
[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 23(+21) η -> 0.177 (current 23 collisions, best 12 collisions)
[ Info: @epoch 51(+21) η -> 0.125 (current 13 collisions, best 12 collisions)
[ Info: @epoch 83(+21) η -> 0.088 (current 17 collisions, best 10 collisions)
[ Info: @epoch 131(+21) η -> 0.063 (current 13 collisions, best 9 collisions)
[ Info: @epoch 158(+21) η <- 0.088 (collisions 9 ≥ 9)
[ Info: @epoch 187(+21) η -> 0.063 (current 12 collisions, best 9 collisions)
[ Info: @epoch 209(+21) η -> 0.044 (current 14 collisions, best 8 collisions)
[ Info: @epoch 249(+21) η -> 0.031 (current 16 collisions, best 7 collisions)
[ Info: @epoch 277(+21) η <- 0.044 (collisions 12 ≥ 7)
[ Info: @epoch 321(+21) η <- 0.063 (collisions 14 ≥ 8)
[ Info: @epoch 373(+21) η <- 0.088 (collisions 

▸3. try scale = 77.18629412221068. The density is reduced to 0.4721123233768557
fontsize ∈ [8.0, 84.58533715385141]
33 words(56%) are limited to the minimum font size.


┌ Warning: Some words are limited to the maximum font size. Please set a `maxfontsize` in `wordcloud` or set a `maxweight` in `processtext`.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-method.jl:65
[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 22(+21) η -> 0.177 (current 14 collisions, best 8 collisions)
[ Info: @epoch 29(+28), 11(2) collisions, reposition [27] to [(378, 548)]


1221 epochs


[ Info: @epoch 32(+2), 3(1) collisions, reposition [14] to [(402, 681)]


In [22]:
wc = wordcloud(
    processtext(song_tmp, stopwords= union(WordCloud.stopwords_en , ["dusty","almost"]) ), #include some more last moment stop words with the union operator
    mask = loadmask("./silhouette-bald-eagle.png", color="#ff5522"),
    colors = :seaborn_dark,
    angles = (0, 90),
    density = 0.5) |> generate!
println("results are saved to eagle.png")
paint(wc, "eagle.png", background=outline(wc.mask, color="purple", linewidth=2))
generate!(wc)
paint(wc, "alice.svg")

Total words: 166. Unique words: 74. After filtration: 52.
The top 52 words are kept. 
fonts = "SimSun Regular"
mask size: 215×234, content area: 141² (20²/word)
set fontsize ∈ [6.92403839477423, 215]
set density = 0.5
⋯scale=21.89573193394267, density=0.729628459687124	↑
⋯scale=18.125649880180863, density=0.5895036101083033	↑
⋯scale=15.23690656299497, density=0.5027707581227437	↑
fontsize ∈ [6.92403839477423, 23.094590857610967]
41 words(79%) are limited to the minimum font size.


┌ Warning: It seems too crowded. Word size may be seriously distorted. You need to reduce the number of words or set a larger mask. Recommended mask scaling: ratio=2.046.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-method.jl:60


▸1. scale = 15.135537947274644


[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 76(+21) η -> 0.177 (current 34 collisions, best 28 collisions)
[ Info: @epoch 110(+21) η -> 0.125 (current 34 collisions, best 16 collisions)
[ Info: @epoch 145(+4), 8(2) collisions, reposition [49] to [(24, 184)]
[ Info: @epoch 153(+7), 15(2) collisions, reposition [49] to [(144, 144)]
[ Info: @epoch 153, random move [49, 20]
[ Info: @epoch 161(+7), 12(2) collisions, reposition [44] to [(136, 124)]
[ Info: @epoch 162(+21) η -> 0.088 (current 10 collisions, best 2 collisions)
[ Info: @epoch 188(+21) η <- 0.125 (collisions 13 ≥ 2)
[ Info: @epoch 204(+42), 14(2) collisions, reposition [52] to [(92, 96)]


272 epochs
results are saved to eagle.png


[ Info: @epoch 211(+4), 13(1) collisions, reposition [20] to [(56, 174)]
[ Info: @epoch 228(+6), 14(2) collisions, reposition [38] to [(40, 137)]
[ Info: @epoch 228(+21) η -> 0.088 (current 14 collisions, best 7 collisions)
[ Info: @epoch 260(+8), 6(2) collisions, reposition [39] to [(114, 104)]
[ Info: @epoch 266(+2), 1(1) collisions, reposition nothing
[ Info: @epoch 267(+3), 2(2) collisions, reposition [52] to [(92, 96)]


▸1. scale = 15.135537947274644
273 epochs


[ Info: nepoch: 1000, patient: 10
┌ Warning: embed bitmap into SVG. You can set `background=false` to remove background.
└ @ WordCloud ~/.julia/packages/WordCloud/nhgNl/src/wc-helper.jl:94


In [23]:
#import Pkg; Pkg.add("HTTP")

In [24]:
using HTTP

url = "https://en.wikipedia.org/wiki/University_of_Central_Florida"
try
    content = HTTP.request("GET", url).body |> String
    wc = wordcloud(content|>html2text|>processtext,style=:gathering,angles=-45:45, centerlargestword=true)|>generate!
    
    println("results are ucf's wiki.png")
    paint(wc, "fromweb.png")
    wc
    generate!(wc)
    paint(wc, "web.svg")
catch e
    println(e)
end

Total words: 17064. Unique words: 3112. After filtration: 2997.
The top 500 words are kept. 
color scheme: :tableau_jewel_bright, random size: 3
shape(box, 1270, 782, cornerradius=343, color=(0.991, 0.967, 0.978), padding=94, centerlargestword=true)
MethodError(Luxor.var"#box##kw"(), ((action = :fill, centerlargestword = true), Luxor.box, Luxor.Point(0.0, 0.0), 1270, 782, 343), 0xffffffffffffffff)


In [25]:
mask = rendertext("U.C.F.", 1000, border=10, color=0.9, backgroundcolor=0.98, type=:svg, font="Verdana")
words = repeat(["Go","Knights","!","cool times","great weather"], 200)
weights = repeat([1], length(words))
wc = wordcloud(
        words, weights, 
        mask = mask,
        angles = [0,30,45,90,180,270,340,0,0],
        colors = ("#4465B0", "#EFA90A", "#5D1115", "#159311", "#002010"),
        density=0.55,
        ) |> generate!
println("results are saved to lettermask.svg")
paint(wc, "lettermask.svg" , background=false)



fonts = "Segoe UI Bold"
mask size: 777×2625, content area: 681² (22²/word)
set fontsize ∈ [7.619161699294746, 777]
set density = 0.55
⋯scale=25.26990057360733, density=0.6348013513833592	↑
⋯scale=23.521551058046118, density=0.4998309694173074	↓
⋯scale=24.18618183784488, density=0.5699194466993818	↑
fontsize ∈ [9.341661603849394, 9.341661603849394]
▸1. scale = 23.999163194526275


[ Info: nepoch: 1000, patient: 10
[ Info: @epoch 60(+21) η -> 0.177 (current 649 collisions, best 608 collisions)
[ Info: [974] are out of bounds
[ Info: @epoch 123(+12), 114(50) collisions, reposition [974] to [(2052, 2966)]
[ Info: @epoch 146(+10), 106(26) collisions, reposition [938] to [(1810, 791)]
[ Info: @epoch 182(+10), 29(27) collisions, reposition [918, 885, 651] to [(2310, 1227), (2206, 784), (1801, 1201)]
[ Info: @epoch 193(+10), 91(43) collisions, reposition [991, 866, 813] to [(2146, 1241), (1990, 2973), (1697, 3164)]
[ Info: @epoch 193(+21) η -> 0.125 (current 91 collisions, best 23 collisions)
[ Info: @epoch 208(+3), 6(1) collisions, reposition nothing
[ Info: @epoch 209(+4), 5(3) collisions, reposition nothing
[ Info: @epoch 209, random move [672, 501, 361]
[ Info: @epoch 212(+2), 5(1) collisions, reposition nothing
[ Info: @epoch 212, random move [922]
[ Info: @epoch 213(+3), 4(1) collisions, reposition [671] to [(2325, 2158)] (forced)
[ Info: @epoch 217(+3), 14(1) co

232 epochs
results are saved to lettermask.svg
